# Generated by Django 5.0 on 2023-12-12 18:07

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to=Main.models.get_Cover_letter_filepath),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=Main.models.get_CV_filepath),
        ),
    ]
