# Generated by Django 5.0 on 2023-12-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_applicant_cover_letter_alter_applicant_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.TextField(default='bdiouipierre@gmail.com'),
        ),
    ]
