# Generated by Django 5.0 on 2023-12-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_applicant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('content', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
