# Generated by Django 5.0 on 2023-12-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('callback_request', models.BooleanField(default=False)),
            ],
        ),
    ]
